github/dependency-submission-toolkit

- .github/workflows/dependency-submission-example.yml
This PR adds write permissions to the example Action, following the guidelines in the [submission API](https://github.com/actions/go-dependency-submission#example) examples.
> Adding write permissions to the example Action

- package-lock.json
- src/snapshot.test.ts
- src/snapshot.ts
https://docs.github.com/en/rest/dependency-graph/dependency-submission#create-a-snapshot-of-dependencies-for-a-repository
```
Error: HTTP Status 422 for request POST https://api.github.com/repos/smorimoto/opam-dependency-submission/dependency-graph/snapshots
Error: Response body:
{
"message": "Invalid request.\n\nInvalid property /job/id: `3116879171` is not of type `string`.",
"documentation_url": "https://docs.github.com/rest/reference/dependency-graph#create-a-snapshot-of-dependencies-for-a-repository"
}
Error: Invalid request.
```
> Fix possible exceptions by matching the type of Snapshot job to the spec

- src/snapshot.ts
I think we should use `github.getOctokit` instead of `new Octokit` to obtain an Octokit instance that works well with GitHub Enterprise.
See also: https://github.com/actions/toolkit/tree/main/packages/github#readme
> Use github.getOctokit

- CONTRIBUTING.md
- package-lock.json
- package.json
Adding a `CONTRIBUTING.md` outlining the basic steps to run tests and do local development. It also includes instructions on how to release a new version, which could be helpful for other folks getting involved with the project.
This document was copy/pasted from another project and needs to be tweaked/improved for this specific tool, but I feel it's better than nothing.
> Adding a contributor's guide

- package-lock.json
- package.json
Update `@actions/core` to v1.10.0 to replace the deprecated `set-output` method call
Find more details here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
---
This will resolve the deprecation warning being logged via the following `setOutput` API call: https://github.com/github/dependency-submission-toolkit/blob/main/src/snapshot.ts#L142
> Update `@actions/core` to fix deprecated `set-output` usage

- .github/workflows/dependency-submission-example.yml
- .github/workflows/test.yml
- example/package.json
- package-lock.json
- package.json
- src/snapshot.ts
Updates dependencies (`@vercel/ncc` in particular) so builds can succeed.
`octokit` was updated to include some clever typing information based on the endpoint being requested. This required a change in our use of octokit to POST a snapshot.
Includes other fixes caused by build-tool bugs.
> Update build dependencies, update octokit request

- package-lock.json
- package.json
- src/snapshot.test.ts
- src/snapshot.ts
As noted in [the Actions docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), `context.sha` can represent different things in different event types. In a `pull_request` event, it happens _not_ to be the sha of the head commit for some reason. Instead, in those cases you're meant to get the head sha from the pull_request payload.
This PR introduces a helper function, `shaFromContext`, that matches on the event type and gets the correct sha for the snapshot. I've also taken the liberty of doing a few quick test refactors.
For prior art, see:
* [similar code in the DR action](https://github.com/actions/dependency-review-action/blob/e3fb5152be474702523c77d8f5ecd4c0a5bde872/src/git-refs.ts#L10-L19)
* [my PR for …
> Get the right SHA for the snapshot depending on the event type

- .github/workflows/dependency-submission-example.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- action.yml
- package-lock.json
- package.json
- tsup.config.ts
Node 16 is EOL, this PR upgrades the Action to Node 20 and bumps the major version.
> Upgrade to Node 20 for 2.0.0

- src/index.ts
```ts
export {
BuildTarget,
Manifest,
Package,
PackageCache,
Snapshot,
submitSnapshot
}
```
```ts
export {
BuildTarget,
type DependencyRelationship,
type DependencyScope,
type Detector,
type Job,
Manifest,
Package,
PackageCache,
Snapshot,
jobFromContext,
shaFromContext,
submitSnapshot
}
```
> Expose all public APIs

- example/package.json
- package-lock.json
- package.json
Correct unused or unlisted dependencies.
Although it was not intended, this reduces the size of the package 🤷‍♂️
```
CJS dist/index.cjs     7.53 KB
ESM dist/index.js     6.82 KB
```
```
CJS dist/index.cjs     4.94 KB
ESM dist/index.js     4.21 KB
```
> Update npm deps

- README.md
- biome.json
- example/package.json
- package-lock.json
- package.json
> Prepare 2.0.3

- package-lock.json
- package.json
483d316 introduced a fix for a low sev vulnerability in `undici`. This PR bumps the version number in `package.json` so we can publish a new release.
> Update package.json to 2.0.4

- ownership.yaml
Update the executive sponsor to `@nerdneha`. Sorry for the churn. We are aligning with best practice and setting the sponsor to be a VP. :bow:
> Update exec sponsor to @nerdneha

- package-lock.json
- package.json
Update packages packages that have esbuild as transitive dependency.
Dependaot alert https://github.com/github/dependency-submission-toolkit/security/dependabot/36
> Upgrade vitest and esbuild

- package-lock.json
- package.json
Override the `esbuild` version for all transitive dependencies to get rid of security vulnerability.
https://github.com/github/dependency-submission-toolkit/security/dependabot/36
> Explicitly override esbuild to non-vulnerable version

- .github/dependabot.yml
Currently Dependabot provides security checks for npm ecosystem, but it's not explicitly enabled, causing confusion in the security alerts page.
E.g. [this alert](https://github.com/github/dependency-submission-toolkit/security/dependabot/42) currently looks like this:
The idea is that configuring Dependabot to explicitly support npm ecosystem would fix this and similar issues going forward.
> Add npm to Dependabot

- package-lock.json
- package.json
Overrides the `@octokit/request-error` dependency to a non-vulnerable version.
https://github.com/github/dependency-submission-toolkit/security/dependabot/43
> Explicitly override @octokit/request-error to a non-vulnerable version

- package-lock.json
- package.json
Preparing for a new release. All of the changes since 2.0.4 are dependency updates or non-code updates, so 2.0.5 is the most appropriate next version number.
Closes a security finding.
> Update version to 2.0.5

- .github/workflows/publish.yml
- .github/workflows/test.yml
Addresses
- https://github.com/github/dependency-submission-toolkit/security/code-scanning/14
- https://github.com/github/dependency-submission-toolkit/security/code-scanning/13
_What issues does this PR close or relate to?_
> Add permissions to publish.yml and test.yml

- package-lock.json
- package.json
_Describe the purpose of this pull request_
Uses an override to upgrade Undici packages to a non-vulnerable version
_What issues does this PR close or relate to?_
- Relates to: https://github.com/github/dependency-submission-toolkit/security/dependabot/53
> Upgrade Undici to 5.29.0
